import { ExecutionEvent } from "@/types/execution";

export const run = {
  id: "run_checkout_042",
  title: "Investigate checkout conversion drop",
  task: "Find why checkout conversion fell after the EU pricing release and recommend a safe fix.",
  startedAt: "Today, 10:32 AM",
  duration: "4m 18s"
  , provider: "curated" as const
};

export const events: ExecutionEvent[] = [
  { id: "scope", sequence: 1, phase: "Plan", title: "Frame the investigation", timestamp: "10:32:04", duration: "18s", status: "completed", prompt: "Investigate the conversion drop. Start by validating the metric, then compare recent changes before proposing a fix.", input: "Alert: EU checkout conversion decreased from 4.8% to 2.1% after the pricing release.", output: "I will validate the drop by region and device, compare releases, then inspect checkout errors around the release window.", toolCalls: [{ name: "metrics.query", summary: "Segmented conversion by market and device", status: "success" }], metadata: { latency: "18.2s", tokens: "1,284", model: "gpt-5.6" }, insight: "The agent narrowed the scope before looking for a cause, avoiding a misleading global average.", position: { x: 0, y: 110 } },
  { id: "validate", sequence: 2, phase: "Research", title: "Validate the signal", timestamp: "10:32:22", duration: "41s", status: "completed", prompt: "Verify whether the conversion decline is isolated and identify the first affected cohort.", input: "Conversion, sessions, and checkout-start metrics for the last 14 days.", output: "The decline begins at 09:07 UTC and affects EU desktop checkout only. Traffic and checkout starts are stable, so this is a completion failure.", toolCalls: [{ name: "metrics.query", summary: "Compared funnel stages across regions", status: "success" }, { name: "release.lookup", summary: "Matched first affected minute to release", status: "success" }], metadata: { latency: "41.0s", tokens: "2,048", model: "terra/large" }, insight: "Stable checkout starts ruled out acquisition and pricing-discovery hypotheses.", position: { x: 270, y: 30 } },
  { id: "compare", sequence: 3, phase: "Analysis", title: "Compare the release", timestamp: "10:33:03", duration: "56s", status: "completed", prompt: "Inspect changes in the EU pricing release that could affect checkout completion.", input: "Release 2026.07.16.3 diff and feature-flag history.", output: "The release introduced tax-inclusive display prices and a new VAT validation payload for EU orders. The rollout is 100% in EU, 0% elsewhere.", toolCalls: [{ name: "git.diff", summary: "Read pricing-release checkout changes", status: "success" }, { name: "flags.get", summary: "Checked regional rollout", status: "success" }], metadata: { latency: "56.4s", tokens: "3,762", model: "terra/large" }, insight: "The exact regional rollout made the VAT payload the highest-value hypothesis.", position: { x: 530, y: 110 } },
  { id: "inspect", sequence: 4, phase: "Evidence", title: "Inspect checkout failures", timestamp: "10:33:59", duration: "1m 22s", status: "completed", prompt: "Find errors correlated with failed EU desktop checkout attempts after the release.", input: "Browser error stream, payment API responses, and anonymized checkout records.", output: "87% of failed sessions contain `VAT_COUNTRY_MISMATCH`. The client sends `country: UK` for all GB addresses, but the payment API now requires `GB`.", toolCalls: [{ name: "logs.search", summary: "Found correlated checkout validation errors", status: "success" }, { name: "api.replay", summary: "Reproduced failure using a GB address", status: "success" }], metadata: { latency: "82.1s", tokens: "4,106", model: "terra/large" }, insight: "Correlation plus reproduction turned a plausible hypothesis into a verified root cause.", position: { x: 790, y: 30 } },
  { id: "recommend", sequence: 5, phase: "Review", title: "Recommend a safe fix", timestamp: "10:35:21", duration: "1m 01s", status: "completed", prompt: "Provide a safe remediation, mitigation, and verification plan based only on verified evidence.", input: "Verified GB country-code mismatch; EU rollout is active.", output: "Immediately disable the VAT payload flag for GB, normalize ISO alpha-2 country codes client-side, add an API contract test, and monitor conversion plus validation errors for 30 minutes.", toolCalls: [{ name: "flags.update", summary: "Prepared a scoped GB rollback", status: "success" }, { name: "test.generate", summary: "Drafted country-code contract coverage", status: "success" }], metadata: { latency: "61.5s", tokens: "2,879", model: "gpt-5.6" }, insight: "The proposed rollback is narrowly scoped and preserves the rest of the EU release.", position: { x: 1050, y: 110 } }
];
